# Generated by Django 5.0.3 on 2025-06-06 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_applicant_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='resume',
        ),
        migrations.AddField(
            model_name='resume',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='api.applicant'),
            preserve_default=False,
        ),
    ]
