# Generated by Django 5.0.3 on 2025-06-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_applicant_resume_resume_applicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='page_no',
            new_name='no_of_pages',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='predicted_field',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='reco_field',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='recommended_skills',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='resume_score',
        ),
        migrations.AddField(
            model_name='analysis',
            name='educational_attainment',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysis',
            name='educational_institutions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysis',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='experience_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='experience_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='experience_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='predicted_job_categories',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysis',
            name='recommended_jobs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysis',
            name='years_of_experience',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
