# Generated by Django 5.0.3 on 2025-06-10 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_page_no_analysis_no_of_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='api.analysis'),
        ),
    ]
